DO NOT MERGE ANYWHERE: Update Health Connect Atoms to match latest main.
Host in the CtsHealthConnectHostTestCases is running the tests from outdated protos which is causing NoSuchMethodError Error. For example:
java.lang.NoSuchMethodError: 'boolean com.android.os.healthfitness.api.HealthConnectUsageStats.getIsMonthlyActiveUser()' at android.healthconnect.cts.logging.HealthConnectDailyLogsStatsTests.testIsUserActive_insertRecord_userMonthlyActiveNextDay(HealthConnectDailyLogsStatsTests.java:163)

Test: atest
Bug: 358006651
Change-Id: I8fb98a0edfa5201863fb690de68117648371a907